CRITICAL - 2024-05-02 01:01:48 --> ErrorException: Attempt to read property "errno" on bool
[Method: POST, Route: blog]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 580.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(580): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "errno" on bool', 'D:\\xampp\\htdocs\\ci4\\system\\Database\\MySQLi\\Connection.php', 580)
 2 SYSTEMPATH\Model.php(915): CodeIgniter\Database\MySQLi\Connection->error()
 3 APPPATH\Controllers\Blog.php(29): CodeIgniter\Model->__call('error', [])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Blog->create()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-02 01:02:23 --> ErrorException: Attempt to read property "errno" on bool
[Method: POST, Route: blog]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 580.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(580): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "errno" on bool', 'D:\\xampp\\htdocs\\ci4\\system\\Database\\MySQLi\\Connection.php', 580)
 2 SYSTEMPATH\Model.php(915): CodeIgniter\Database\MySQLi\Connection->error()
 3 APPPATH\Controllers\Blog.php(29): CodeIgniter\Model->__call('error', [])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Blog->create()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-02 01:02:28 --> ErrorException: Attempt to read property "errno" on bool
[Method: POST, Route: blog]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 580.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(580): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "errno" on bool', 'D:\\xampp\\htdocs\\ci4\\system\\Database\\MySQLi\\Connection.php', 580)
 2 SYSTEMPATH\Model.php(915): CodeIgniter\Database\MySQLi\Connection->error()
 3 APPPATH\Controllers\Blog.php(29): CodeIgniter\Model->__call('error', [])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Blog->create()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
CRITICAL - 2024-05-02 13:29:39 --> ParseError: syntax error, unexpected end of file
[Method: GET, Route: /]
in APPPATH\Config\Routes.php on line 10.
 1 SYSTEMPATH\CodeIgniter.php(823): CodeIgniter\Router\RouteCollection->loadRoutes()
 2 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->tryToRouteIt(null)
 3 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 4 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 6 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
 7 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\xampp\\htdocs\\ci4\\public\\index.php')
ERROR - 2024-05-02 13:30:12 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\xampp\htdocs\ci4\system\Model.php(207): CodeIgniter\Database\BaseBuilder->get()
#5 D:\xampp\htdocs\ci4\system\BaseModel.php(610): CodeIgniter\Model->doFind(true, 'test')
#6 D:\xampp\htdocs\ci4\app\Controllers\Blog.php(19): CodeIgniter\BaseModel->find('test')
#7 D:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Blog->show('test')
#8 D:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
#9 D:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\xampp\htdocs\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#11 D:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\xampp\htdocs\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\xampp\\htdocs...')
#14 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4\system\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\xampp\htdocs\ci4\system\Model.php(207): CodeIgniter\Database\BaseBuilder->get()
#4 D:\xampp\htdocs\ci4\system\BaseModel.php(610): CodeIgniter\Model->doFind(true, 'test')
#5 D:\xampp\htdocs\ci4\app\Controllers\Blog.php(19): CodeIgniter\BaseModel->find('test')
#6 D:\xampp\htdocs\ci4\system\CodeIgniter.php(933): App\Controllers\Blog->show('test')
#7 D:\xampp\htdocs\ci4\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
#8 D:\xampp\htdocs\ci4\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 D:\xampp\htdocs\ci4\system\Boot.php(312): CodeIgniter\CodeIgniter->run()
#10 D:\xampp\htdocs\ci4\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#11 D:\xampp\htdocs\ci4\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#12 D:\xampp\htdocs\ci4\system\Commands\Server\rewrite.php(49): require_once('D:\\xampp\\htdocs...')
#13 {main}
CRITICAL - 2024-05-02 13:30:12 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
[Method: GET, Route: blog/test]
in SYSTEMPATH\Database\BaseConnection.php on line 457.
 1 SYSTEMPATH\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `blog`
WHERE `blog`.`deleted_at` IS NULL
AND `blog`.`id` = :blog.id:', [...], false)
 3 SYSTEMPATH\Model.php(207): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(610): CodeIgniter\Model->doFind(true, 'test')
 5 APPPATH\Controllers\Blog.php(19): CodeIgniter\BaseModel->find('test')
 6 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Blog->show('test')
 7 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
 8 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 9 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
11 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
12 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\xampp\\htdocs\\ci4\\public\\index.php')
CRITICAL - 2024-05-02 13:38:36 --> ErrorException: Attempt to read property "errno" on bool
[Method: POST, Route: blog/]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 580.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(580): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "errno" on bool', 'D:\\xampp\\htdocs\\ci4\\system\\Database\\MySQLi\\Connection.php', 580)
 2 SYSTEMPATH\Model.php(915): CodeIgniter\Database\MySQLi\Connection->error()
 3 APPPATH\Controllers\Blog.php(29): CodeIgniter\Model->__call('error', [])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Blog->create()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\xampp\\htdocs\\ci4\\public\\index.php')
CRITICAL - 2024-05-02 13:39:12 --> ErrorException: Attempt to read property "errno" on bool
[Method: POST, Route: blog/]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 580.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(580): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "errno" on bool', 'D:\\xampp\\htdocs\\ci4\\system\\Database\\MySQLi\\Connection.php', 580)
 2 SYSTEMPATH\Model.php(915): CodeIgniter\Database\MySQLi\Connection->error()
 3 APPPATH\Controllers\Blog.php(29): CodeIgniter\Model->__call('error', [])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Blog->create()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\xampp\\htdocs\\ci4\\public\\index.php')
CRITICAL - 2024-05-02 13:40:50 --> ErrorException: Attempt to read property "errno" on bool
[Method: POST, Route: blog/]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 580.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(580): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "errno" on bool', 'D:\\xampp\\htdocs\\ci4\\system\\Database\\MySQLi\\Connection.php', 580)
 2 SYSTEMPATH\Model.php(915): CodeIgniter\Database\MySQLi\Connection->error()
 3 APPPATH\Controllers\Blog.php(29): CodeIgniter\Model->__call('error', [])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Blog->create()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\xampp\\htdocs\\ci4\\public\\index.php')
CRITICAL - 2024-05-02 13:41:04 --> ErrorException: Attempt to read property "errno" on bool
[Method: POST, Route: blog/]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 580.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(580): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "errno" on bool', 'D:\\xampp\\htdocs\\ci4\\system\\Database\\MySQLi\\Connection.php', 580)
 2 SYSTEMPATH\Model.php(915): CodeIgniter\Database\MySQLi\Connection->error()
 3 APPPATH\Controllers\Blog.php(29): CodeIgniter\Model->__call('error', [])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Blog->create()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\xampp\\htdocs\\ci4\\public\\index.php')
CRITICAL - 2024-05-02 13:44:01 --> ErrorException: Attempt to read property "errno" on bool
[Method: POST, Route: blog/]
in SYSTEMPATH\Database\MySQLi\Connection.php on line 580.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(580): CodeIgniter\Debug\Exceptions->errorHandler(2, 'Attempt to read property "errno" on bool', 'D:\\xampp\\htdocs\\ci4\\system\\Database\\MySQLi\\Connection.php', 580)
 2 SYSTEMPATH\Model.php(915): CodeIgniter\Database\MySQLi\Connection->error()
 3 APPPATH\Controllers\Blog.php(29): CodeIgniter\Model->__call('error', [])
 4 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\Blog->create()
 5 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Blog))
 6 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 SYSTEMPATH\Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
 9 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
10 SYSTEMPATH\Commands\Server\rewrite.php(49): require_once('D:\\xampp\\htdocs\\ci4\\public\\index.php')
ERROR - 2024-05-02 13:51:25 --> Error connecting to the database: mysqli_sql_exception: Unknown database 'ci4' in D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('localhost', 'root', Object(SensitiveParameterValue), 'ci4', 3306, '', 0)
#1 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(1471): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#4 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(1490): CodeIgniter\Database\BaseConnection->listTables()
#5 D:\xampp\htdocs\ci4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#6 D:\xampp\htdocs\ci4\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#7 D:\xampp\htdocs\ci4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#8 D:\xampp\htdocs\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#9 D:\xampp\htdocs\ci4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#10 D:\xampp\htdocs\ci4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#11 D:\xampp\htdocs\ci4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#12 D:\xampp\htdocs\ci4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#13 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Unknown database 'ci4' in D:\xampp\htdocs\ci4\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(1471): CodeIgniter\Database\BaseConnection->query('SHOW TABLES FRO...')
#3 D:\xampp\htdocs\ci4\system\Database\BaseConnection.php(1490): CodeIgniter\Database\BaseConnection->listTables()
#4 D:\xampp\htdocs\ci4\system\Database\MigrationRunner.php(759): CodeIgniter\Database\BaseConnection->tableExists('migrations')
#5 D:\xampp\htdocs\ci4\system\Database\MigrationRunner.php(163): CodeIgniter\Database\MigrationRunner->ensureTable()
#6 D:\xampp\htdocs\ci4\system\Commands\Database\Migrate.php(85): CodeIgniter\Database\MigrationRunner->latest(NULL)
#7 D:\xampp\htdocs\ci4\system\CLI\Commands.php(70): CodeIgniter\Commands\Database\Migrate->run(Array)
#8 D:\xampp\htdocs\ci4\system\CLI\Console.php(48): CodeIgniter\CLI\Commands->run('migrate', Array)
#9 D:\xampp\htdocs\ci4\system\Boot.php(338): CodeIgniter\CLI\Console->run()
#10 D:\xampp\htdocs\ci4\system\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
#11 D:\xampp\htdocs\ci4\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
#12 {main}
ERROR - 2024-05-02 16:05:40 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:05:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:06:32 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:06:32 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:06:41 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:06:41 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:07:37 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:07:37 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:07:59 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:07:59 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:09:03 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:09:03 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:09:05 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:09:05 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:10:17 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:10:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:11:10 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:11:10 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:11:11 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:11:11 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:13:57 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:187
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(187): mysqli->real_connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: NO) in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:231
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#3 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#4 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#7 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#9 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#10 {main}
CRITICAL - 2024-05-02 16:13:57 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: NO)
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 457.
 1 SYSTEMPATH/Database/BaseConnection.php(604): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 3 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 5 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 6 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 7 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 9 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
ERROR - 2024-05-02 16:14:58 --> mysqli_sql_exception: Table 'sql_talha_logon_.attendance' doesn't exist in /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php:308
Stack trace:
#0 /www/wwwroot/talha_logon/API/system/Database/MySQLi/Connection.php(308): mysqli->query()
#1 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute()
#2 /www/wwwroot/talha_logon/API/system/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery()
#3 /www/wwwroot/talha_logon/API/system/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
#4 /www/wwwroot/talha_logon/API/app/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
#5 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(933): App\Controllers\Attendance->index()
#6 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
#7 /www/wwwroot/talha_logon/API/system/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
#8 /www/wwwroot/talha_logon/API/system/Boot.php(312): CodeIgniter\CodeIgniter->run()
#9 /www/wwwroot/talha_logon/API/system/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
#10 /www/wwwroot/talha_logon/API/public/index.php(56): CodeIgniter\Boot::bootWeb()
#11 {main}
CRITICAL - 2024-05-02 16:14:58 --> CodeIgniter\Database\Exceptions\DatabaseException: Table 'sql_talha_logon_.attendance' doesn't exist
[Method: GET, Route: attendance]
in SYSTEMPATH/Database/BaseConnection.php on line 676.
 1 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 2 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 3 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 4 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 5 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 6 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 8 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
CRITICAL - 2024-05-02 16:14:58 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Table 'sql_talha_logon_.attendance' doesn't exist
in SYSTEMPATH/Database/MySQLi/Connection.php on line 313.
 1 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute()
 2 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery()
 3 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 4 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 5 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 6 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 7 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 8 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
10 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
CRITICAL - 2024-05-02 16:14:58 --> [Caused by] mysqli_sql_exception: Table 'sql_talha_logon_.attendance' doesn't exist
in SYSTEMPATH/Database/MySQLi/Connection.php on line 308.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(308): mysqli->query()
 2 SYSTEMPATH/Database/BaseConnection.php(722): CodeIgniter\Database\MySQLi\Connection->execute()
 3 SYSTEMPATH/Database/BaseConnection.php(636): CodeIgniter\Database\BaseConnection->simpleQuery()
 4 SYSTEMPATH/Database/BaseBuilder.php(1629): CodeIgniter\Database\BaseConnection->query()
 5 APPPATH/Controllers/Attendance.php(63): CodeIgniter\Database\BaseBuilder->get()
 6 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->index()
 7 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 8 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 9 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
10 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
11 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
CRITICAL - 2024-05-02 16:22:02 --> Error: Call to undefined function App\Controllers\get_current_utc_time()
[Method: POST, Route: attendance]
in APPPATH/Controllers/Attendance.php on line 130.
 1 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->create()
 2 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 3 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 4 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 6 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
CRITICAL - 2024-05-02 16:22:33 --> Error: Call to undefined function App\Controllers\get_current_utc_time()
[Method: POST, Route: attendance]
in APPPATH/Controllers/Attendance.php on line 130.
 1 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->create()
 2 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 3 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 4 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 6 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
CRITICAL - 2024-05-02 16:22:44 --> Error: Call to undefined function App\Controllers\NOW()
[Method: POST, Route: attendance]
in APPPATH/Controllers/Attendance.php on line 139.
 1 SYSTEMPATH/CodeIgniter.php(933): App\Controllers\Attendance->create()
 2 SYSTEMPATH/CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController()
 3 SYSTEMPATH/CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest()
 4 SYSTEMPATH/Boot.php(312): CodeIgniter\CodeIgniter->run()
 5 SYSTEMPATH/Boot.php(67): CodeIgniter\Boot::runCodeIgniter()
 6 FCPATH/index.php(56): CodeIgniter\Boot::bootWeb()
